# Matrix Multiplication
- matrix A of size (3,3) = (m,n)
- matrix B of size (3,3) = (p,q)
- matrix multipliation rules. n=p and the output matrix shape will (m,q)

In [2]:
A = [[1,2],[2,3]]

In [2]:
import numpy as np

In [7]:
A = np.array(A)

In [14]:
A

array([[1, 2],
       [2, 3]])

In [18]:
m,n = A.shape

In [15]:
B = np.array([[2,3],[1,2]])

In [21]:
B

array([[2, 3],
       [1, 2]])

In [17]:
type(B)

numpy.ndarray

In [19]:
p,q = B.shape

In [20]:
if n==p:
    print("Matrix Multiplication is possible")
else:
    print("Matrix Multiplication is not possible")

Matrix Multiplication is possible


In [24]:
A[0,0]*B[0,0] + A[0,1]*B[1,0]

4

In [25]:
A[0,0]*B[0,1] + A[0,1]+B[1,1]

7

In [26]:
A[1,0]*B[0,0] + A[1,1]*B[1,0]

7

In [27]:
A[1,0]*B[0,1] + A[1,1]*B[1,1]

12

In [ ]:
# What is the no of multiplications required for matrix multiplication of Matrix A
#with size m,n and Matrix B with size p,q
# No of steps = m*q
# no of multipliations in Each step n/p Since n==p
# Total no of multiplications =  m*q*n
# Total no of Additions = m*q*(n-1)
# Total no of Instructions for matric multiplication  = m*q*n + (m*q*(n-1))
# One Addition instruction will take one clock signal => 1second
# One mutliplication instrucion will take 5 cpu clocks ==> 5seconds
# Time taken by matrix multipliocation = (m*q*n)*5 Seconds + ((m*q*(n-1))*1Second)

In [ ]:
## Irrespective of the size of the matrix numpy matrix multiplocation which will take 2 CPU Clocks (1, multiplication and 1additions)

In [37]:
np.dot(A,B)

array([[ 4,  7],
       [ 7, 12]])

In [28]:
(0,0), (0,1), (1,0), (1,1)

((0, 0), (0, 1), (1, 0), (1, 1))

In [49]:
C = np.zeros((m,q))

In [50]:
C

array([[0., 0.],
       [0., 0.]])

In [52]:
A.shape

(5, 2)

In [53]:
A.shape[0]

5

In [55]:
for row in range(A.shape[0]):
    for column in range(B.shape[1]):
        for k in range(A.shape[1]):
            C[row,column] += A[row,k]*B[k,column]
C

IndexError: index 2 is out of bounds for axis 0 with size 2

In [35]:
C

array([[ 4.,  7.],
       [ 7., 12.]])

In [44]:
A = np.random.rand(5,2)

In [45]:
A.shape

(5, 2)

In [2]:
A = np.array([1,2,3])

In [3]:
A

array([1, 2, 3])

In [7]:
B = [1,2,3]

In [8]:
for i in range(len(B)):
    B[i] += 1

In [9]:
B

[2, 3, 4]

In [10]:
B+1

TypeError: can only concatenate list (not "int") to list

In [11]:
A

array([1, 2, 3])

In [12]:
A+1

array([2, 3, 4])

In [13]:
A + [1,1,1]

array([2, 3, 4])

In [14]:
A

array([1, 2, 3])

In [15]:
1

1

In [16]:
A

array([1, 2, 3])

In [22]:
B = np.array([2,3,4])

In [18]:
A,B

(array([1, 2, 3]), array([2, 3, 4]))

In [19]:
A+B

array([3, 5, 7])

In [20]:
A

array([1, 2, 3])

In [23]:
C = np.array([1])

In [24]:
A+C

array([2, 3, 4])

In [25]:
D = np.array([1,2])

In [26]:
A+D

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [28]:
A,B

(array([1, 2, 3]), array([2, 3, 4]))

In [32]:
np.sum([A,B]) # Sequential Addition operation of all elements in all arrays.

15

In [29]:
np.sum([A,B],axis=1)

array([6, 9])

In [36]:
A,A.shape

(array([1, 2, 3]), (3,))

In [42]:
A.shape

(3,)

In [38]:
X = np.array([[1,2,3],[2,3,3]])

In [40]:
X

array([[1, 2, 3],
       [2, 3, 3]])

In [47]:
X.ndim

2

In [48]:
A.ndim

1

In [39]:
X.shape

(2, 3)

In [37]:
B,B.shape

(array([2, 3, 4]), (3,))

In [44]:
E = np.array([[1,2],[2,3]])
E,E.shape

(array([[1, 2],
        [2, 3]]),
 (2, 2))

In [43]:
np.hstack([A,B])

array([1, 2, 3, 2, 3, 4])

In [50]:
A.ndim,E.ndim

(1, 2)

In [52]:
np.vstack([A,B])

array([[1, 2, 3],
       [2, 3, 4]])

In [63]:
np.sum([A,B])

15

In [59]:
np.multiply(A,B)

array([ 2,  6, 12])

In [61]:
np.divide(A,B)

array([0.5       , 0.66666667, 0.75      ])

In [46]:
np.hstack([A,E])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [64]:
np.column_stack([A,B])

array([[1, 2],
       [2, 3],
       [3, 4]])

In [68]:
list(range(10,100,5))

[10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]

In [67]:
np.arange(10,100,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [72]:
Z = np.random.rand(10,10) # Normal Distribution

In [71]:
Z.shape

(10, 10)

In [103]:
np.random.seed(100) ## ML model Weights Bias. 

In [104]:
np.random.randint(10,100)

18

In [105]:
A.shape

(3,)

In [107]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [108]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [109]:
np.full((2,2),2)

array([[2, 2],
       [2, 2]])

In [15]:
O = np.random.rand(2)

In [16]:
O

array([0.13202789, 0.03651757])

In [13]:
O.ndim

1

In [38]:
A = np.random.rand(2,3)
A.ndim

2

In [50]:
A.shape

(2, 3)

In [42]:
A

array([[0.00529469, 0.21061371, 0.51930035],
       [0.44443667, 0.67058404, 0.45482068]])

In [44]:
A[1,:2]

array([0.44443667, 0.67058404])

In [45]:
A[0,1:]

array([0.21061371, 0.51930035])

In [49]:
A[:2,1:]

array([[0.21061371, 0.51930035],
       [0.67058404, 0.45482068]])

In [51]:
RubiksCube = np.random.rand(3,3,3)

In [52]:
RubiksCube

array([[[0.39824843, 0.02479525, 0.78337676],
        [0.94153398, 0.25253086, 0.20293577],
        [0.58293526, 0.50721075, 0.8393994 ]],

       [[0.79048775, 0.63251763, 0.66015879],
        [0.23882388, 0.03494367, 0.63397214],
        [0.1533483 , 0.13254941, 0.14335111]],

       [[0.19938404, 0.11684347, 0.28132269],
        [0.70863836, 0.4335351 , 0.31242426],
        [0.46185303, 0.92329677, 0.77730527]]])

In [57]:
RubiksCube[2]

array([[0.19938404, 0.11684347, 0.28132269],
       [0.70863836, 0.4335351 , 0.31242426],
       [0.46185303, 0.92329677, 0.77730527]])

In [59]:
RubiksCube[1,:2,:2]

array([[0.79048775, 0.63251763],
       [0.23882388, 0.03494367]])

In [63]:
RubiksCube[1,:3,:2]

array([[0.79048775, 0.63251763],
       [0.23882388, 0.03494367],
       [0.1533483 , 0.13254941]])

In [64]:
RubiksCube[1,:2,:3]

array([[0.79048775, 0.63251763, 0.66015879],
       [0.23882388, 0.03494367, 0.63397214]])

In [22]:
B = np.random.rand(3,2,2)

In [54]:
B[0]

array([[0.28274563, 0.32583079],
       [0.6227665 , 0.98665107]])

In [23]:
B.ndim

3

In [ ]:
B

In [25]:
B = np.random.rand(33,2,2)

In [26]:
B.ndim

3

In [31]:
C = np.random.rand(2,4,3,2,2)

In [32]:
C.ndim

5

In [33]:
C

array([[[[[0.91386353, 0.50784501],
          [0.7073014 , 0.23083596]],

         [[0.26501257, 0.80030435],
          [0.67545319, 0.48232151]],

         [[0.68826835, 0.1145654 ],
          [0.16423548, 0.81755535]]],


        [[[0.61521604, 0.17732964],
          [0.89019473, 0.79973665]],

         [[0.57266389, 0.85217327],
          [0.95870843, 0.58804671]],

         [[0.05669205, 0.69994016],
          [0.82837239, 0.89670732]]],


        [[[0.51278135, 0.97490405],
          [0.24013067, 0.1668882 ]],

         [[0.20563855, 0.89503825],
          [0.69813218, 0.72976183]],

         [[0.1308657 , 0.14138368],
          [0.83500424, 0.32760216]]],


        [[[0.16181332, 0.88886708],
          [0.01363979, 0.87437424]],

         [[0.43155835, 0.35343758],
          [0.31359327, 0.11959998]],

         [[0.17745733, 0.44923012],
          [0.76207815, 0.04220558]]]],



       [[[[0.07984432, 0.37527197],
          [0.39380384, 0.64634882]],

         [[0.28959891, 0.018